services:
  xrx-orchestrator:
    build: 
      context: ./xrx-core/orchestrator
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
    env_file: .env
    depends_on:
      - xrx-redis
    networks:
      - xrx-network

  xrx-stt:
    build:
      context: ./xrx-core/stt
    ports:
      - "8001:8001"
    env_file: .env
    networks:
      - xrx-network

  xrx-tts:
    build:
      context: ./xrx-core/tts
    ports:
      - "8002:8002"
    env_file: .env
    networks:
      - xrx-network

  xrx-reasoning:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    env_file: .env
    volumes:
      - ./app:/app
    depends_on:
      - xrx-redis
    networks:
      - xrx-network

  xrx-redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - xrx-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - NODE_ENV=production
    env_file: .env
    depends_on:
      - xrx-orchestrator
      - xrx-reasoning
    networks:
      - xrx-network

volumes:
  redis-data:

networks:
  xrx-network:
    driver: bridge